baseURL: https://www.discoos.org
languageCode: en-us
defaultContentLanguage: en
title: DISCO Open Source
theme: cayman-hugo-theme

# Google analytics
#googleAnalytics: #UA-123456789-1

# Syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: /:contentbasename/

params:
  # Header text, can be markdown
  project_name: DISCO Open Source
  project_tagline: We develop free and open source software for Search and Rescue

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2006-01-02

  # Footer text, can be markdown
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex: true

  # Breakpoints
  large_breakpoint: 64em
  medium_breakpoint: 42em

  # Header colors
  header_heading_color: "#fff"
  header_background_color: "#159957"
  header_background_color_secondary: "#155799"

  # Text colors
  section_headings_color: "#159957"
  body_text_color: "#606c71"
  body_link_color: "#1e6bb8"
  blockquote_text_color: "#819198"

  # Code colors
  code_background_color: "#f3f6fa"
  code_text_color: "#567482"

  # Border colors
  border_color: "#dce6f0"
  table_border_color: "#e9ebec"
  hr_border_color: "#eff0f1"

menu:
  nav:
    - name: Blog
      url: https://medium.com/discoos
      weight: 1
    - name: Projects
      url: /projects/
      weight: 2
    - name: Github
      url: https://github.com/DISCOOS
      weight: 3
    - name: About
      url: /
      weight: 4
